# Generated by Django 4.2.6 on 2023-11-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("petsapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PetUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
